### ISSUE TITLE
add command to clear variables stored clearVar()

### ISSUE THREAD

**Issue by Mordred-LoU** [Lady-Binary/EasyLOU#88]
create command to clear stored variable. such as clearVar(CLICKOBJID) this way programs don't default to old variables when you hit the play button... and/or clear variables when a macro is stopped.

**Comment by Lady-Binary** [comment]
thanks for the feedback @Mordred-LoU !

not sure we can do that with all the variables, as we have to take into account there might be multiple scripts running, or even multiple instances of EasyLOU, but with some of those "temporary" variables we might, like the Click ones, and MouseOver ones.

are you suggesting that because some variable gets stuck?

**Comment by Mordred-LoU** [comment]
@Lady-Binary yes.  FindItem(item, BACKPACKID) is getting stuck when you use item identification.

method:  drag item into backpack using FindItem("unidentified, CLICKOBJID).  use item identification skill to ID the item then repeat search for FindItem("unidentified").. the FINDITEMID[1] will stick and continue to show the item as unidentified even after the item has been identified and should be resulting as nil until the item is Drag(item) and Dropc(item,BACKPACKID)

**Comment by Lady-Binary** [comment]
So, the unidentified problem was because I was grabbing the name from a "wrong" variable.
I should have fixed with #94 

However, it might stil be a good idea to have a ResetVars() option. I cannot do it selectively for the time being, but I will reset all the vars. I'm gonna implement it.

**Comment by Lady-Binary** [comment]
implemented in next release
