### ISSUE TITLE
retrieve permanent objects (e.g. trees and rocks) textures and colors

### ISSUE THREAD

**Issue by moinphyst** [Lady-Binary/EasyLOU#89]
We could use an additional table with the State Permanent Objects to keep from potentially mining a depleted resource or needlessly farming lower level materials.

Adding a table for PERMASTATE would fulfill this need. A rock could be Depleted, Stone, Iron, Copper, Gold, Cobalt or Obsidian and a tree could be Depleted, Wood, Ash or Blightwood.

I've tried a few different approaches where I scan the journal to look for key words like Depleted and Stone. These have definitely helped speed up the gathering process but I believe the suggested solution would be leaps and bounds ahead of it.

-- Thanks for all the hard work you do, this program is awesome and has been a lot of fun to use!

**Comment by Lady-Binary** [comment]
Hi @moinphyst , thank you for your suggestion!

I am afraid these states might be kept on the server side only, and not available at the client. With that, it would be hard to cache them in a variable. Unless you're suggesting this because you have noticed these might be stored somewhere by the client of course.

Other workaround I see, is using a prospector's tool on the permanent object and analyzing the content of the popup.

I'll look into it!

And I'm glad you like the project :+1:

**Comment by thiagomaf** [comment]
@moinphyst I am trying to understand your point. 
Correct me if I am wrong, but knowing or not whether a rock/tree is depleted will not speed up or slow down your rail.... you might go faster from one permanent to the other, but in the end the permanent will respawn in the same time.

Not sure this will speed things up.

**Comment by moinphyst** [comment]
@thiagomaf I am actually more interested in finding out what type of wood a tree will give me. I'm not using a rail like in the example, instead I'm able to walk a general path that harvests trees near the path. Having the ability to ascertain the type of wood a tree would produce would allow me to specifically target those trees along my path and ignore the others. It would also be a bit faster going to the next tree than scanning the journal to look for a "depleted" or "failed" and more reliable than waiting for weight to not change.

So to get back to the point, if I'm walking up to a depleted node anyways, there is little to no benefit. I do not plan to use this method if I am able to know what type of tree I can chop.


@Lady-Binary Thanks for looking into this and sorry I didn't get to this sooner. Unfortunately I'm unable to benefit from the use of the prospect tool as I'm playing on a server that does not have that item. Also, as @thiagomaf mentioned, if you're already at the tree it is hardly of any consequence. I'll try and dig into some of the files as well. This would be a pretty big benefit for me.

**Comment by thiagomaf** [comment]
Hmmm.... so I am assuming you are talking about the LoA? Am I correct? 
Only in LoA you are able to get the kind of rock (but not wood) from 'its appearence'. In case of LoU I understand you are not expected to know about the kind of tree/rock without prospecting it - so in a sense, besides rocks in LoA, the task you are proposing seems to me like not supposed to be possible - unless cheating is in the scope of the software.

@moinphyst I am sorry, I am really not trying to put your idea down.
Please let me know if I misunderstood your point. As is, I am not convinced that this should be implemented.

**Comment by moinphyst** [comment]
@thiagomaf there is actually a visual difference between the trees. The color of the leaves are more red instead of green the higher level the tree (there are only the three). [Lumberjacking Wiki Page](https://legendsofaria.gamepedia.com/Lumberjack)

That gives some examples of the visual difference. I've heard others say the visuals don't change but in my experience with LoA that does not seem to be the case and they do actual represent the type of wood you can obtain.

**Comment by thiagomaf** [comment]
@moinphyst hmmmm.... the dilemma grows.
In this case, it is less problematic for LoA-like servers. The question is: what such feature would return in a LoU server? 

I am asking because if in a LoU-like server the only returned value is something also undetermined.... then perhaps your request would not be problematic (i.e. not cheating).

**Comment by moinphyst** [comment]
@thiagomaf That is a valid concern. I think it would come down to what type of information is being sent to the client and I expect it's just pointing it to using a certain color/texture variation in the object. (Unless there is something simpler, I've yet to dive into the games files as I'm still quite wet behind the ears). If that is the case, the only real change LoU users would be able to glean is whether or not a particular tree is depleted.

**Comment by Lady-Binary** [comment]
so, what I was able to do, is to extract information regarding the permanent object's texture and color. you'll find them in a new variable FINDPERMATEXTURE and FINDPERMACOLOR with the new release.

I think we should not be concerned with this - it's not "cheating", because it's actually visual information that already is displayed by the client in the form of tree texture or vein color.

test it please and see if it does the job!

it should be released soon.
